// Generated by pnpm article:sync. Do not edit by hand.
import Article0, {
  article as metadata0,
} from './the-glass-looked-wrong/index.mdx';
import Article1, {
  article as metadata1,
} from './the-tiny-detail-simple-analytics-added-for-screenshots/index.mdx';
import type { ArticleMetadata } from './types';

export const registeredArticles = [
  { Content: Article0, metadata: metadata0 as ArticleMetadata },
  { Content: Article1, metadata: metadata1 as ArticleMetadata },
] as const;
